/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedFuncionariosAdminRouteImport } from './routes/_authenticated/funcionarios-admin'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosAdminRoute =
  AuthenticatedFuncionariosAdminRouteImport.update({
    id: '/funcionarios-admin',
    path: '/funcionarios-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/funcionarios-admin': typeof AuthenticatedFuncionariosAdminRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/funcionarios-admin': typeof AuthenticatedFuncionariosAdminRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/funcionarios-admin': typeof AuthenticatedFuncionariosAdminRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/estoque'
    | '/fechamento'
    | '/financeiro'
    | '/fornecedores'
    | '/funcionarios-admin'
    | '/pdv'
    | '/produtos'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/estoque'
    | '/fechamento'
    | '/financeiro'
    | '/fornecedores'
    | '/funcionarios-admin'
    | '/pdv'
    | '/produtos'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/fechamento'
    | '/_authenticated/financeiro'
    | '/_authenticated/fornecedores'
    | '/_authenticated/funcionarios-admin'
    | '/_authenticated/pdv'
    | '/_authenticated/produtos'
    | '/_authenticated/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios-admin': {
      id: '/_authenticated/funcionarios-admin'
      path: '/funcionarios-admin'
      fullPath: '/funcionarios-admin'
      preLoaderRoute: typeof AuthenticatedFuncionariosAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedFuncionariosAdminRoute: typeof AuthenticatedFuncionariosAdminRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedFuncionariosAdminRoute: AuthenticatedFuncionariosAdminRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
